#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android_App.Resource", IsApplication=true)]

namespace Android_App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_custom_background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int theme_material_noactionbar_background = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int HRImage = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000e
			public const int Cancel = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int CreateAccount = 2131230733;
			
			// aapt resource value: 0x7f080006
			public const int LoginButton = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int PasswordField = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int SignUpButton = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int UsernameField = 2131230722;
			
			// aapt resource value: 0x7f08000a
			public const int editText1 = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int editText2 = 2131230732;
			
			// aapt resource value: 0x7f080005
			public const int gridLayout1 = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int imageView = 2131230720;
			
			// aapt resource value: 0x7f080008
			public const int linearLayout1 = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int textView1 = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int textView2 = 2131230723;
			
			// aapt resource value: 0x7f080009
			public const int textView3 = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int textView4 = 2131230731;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SignUpPage = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
